workflows:
  my-workflow:                   # workflow ID
    name: My workflow name       # workflow name displayed in Codemagic UI
    instance_type: mac_mini_m1   # machine instance type
    max_build_duration: 60       # build duration in minutes (min 1, max 120)
    environment:
     groups:             # Define your environment variables groups here
       - keystore_credentials
       - app_store_credentials
     vars:
       GOOGLE_PLAY_TRACK: "beta"
     flutter: stable   # Define the channel name or version (e.g. v1.13.4)
     xcode: latest     # Define latest, edge or version (e.g. 11.2)
     cocoapods: 1.9.1  # Define default or version
     node: 12.14.0     # Define default, latest, current, lts, carbon (or another stream), nightly or version
     npm: 6.13.7       # Define default, latest, next, lts or version
     ndk: r21d         # Define default or revision (e.g. r19c)
     java: 1.8         # Define default, or platform version (e.g. 11)
     ruby: 2.7.2       # Define default or version
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/Library/Caches/CocoaPods
        - $CM_BUILD_DIR/node_modules
    triggering:
      events:                       # List the events that trigger builds
        - push
        - pull_request
        - tag
      branch_patterns:              # Include or exclude watched branches
        - pattern: '*'
          include: true
        - pattern: develop
          include: false
        - pattern: feature-1
          include: true
          source: true
    scripts:
      - name: Get Flutter Packages
        script: flutter packages pub get
      - name: Build for apk
        script: flutter build apk --release
      - name: Set up key properties
        script: /
          cat >> "$CM_BUILD_DIR/android/key.properties" <<EOF
          storePassword=$CM_KEYSTORE_PASSWORD
          keyPassword=$CM_KEY_PASSWORD
          keyAlias=$CM_KEY_ALIAS
          storeFile=$CM_KEYSTORE_PATH
          EOF
    artifacts: 
      - build/**/outputs/apk/**/*.apk
      - build/**/outputs/**/*.aab
    publishing: 
      email:
        recipients:
          - savith.lal@gmail.com
          
